# Copyright 2021 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.3 on 2021-05-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("greet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=2)),
                ("translation", models.CharField(max_length=20)),
                (
                    "greeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="greet.greeting"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=("greeting", "lang"), name="greeting_lang"
            ),
        ),
    ]
